## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
before_install:
 - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install r-base; else brew install r; fi
os:
  - linux
  - osx
julia:
  - 1.1
  - nightly
notifications:
  email: false
